require.config({
  baseUrl: "/webapp/1.0/web/",
  shim: {
    _: {
      exports: "_"
    },
    B: {
      deps: ["_"],
      exports: "Backbone"
    },
    cBase: {
      exports: "cBase"
    },
    cAjax: {
      exports: "cAjax"
    },
    cView: {
      deps: ["B"],
      exports: "cView"
    }
  },
  paths: {
    text: "res/libs/require.text",
    App: "app/1.0/web/app",
    c: "app/1.0/web/common/c",
    cUtility: "app/1.0/web/common/c.utility",
    cBase: "app/1.0/web/common/c.base",
    cLog: "app/1.0/web/common/c.log",
    cValidate: "app/1.0/web/common/c.validate",
    cSales: "app/1.0/web/common/c.sales",
    cLazyload: "app/1.0/web/common/c.lazyload",
    cListAdapter: "app/1.0/web/common/c.common.listadapter",
    cGeoService: "app/1.0/web/common/c.geo.service",
    rsa: "app/1.0/web/common/c.rsa",
    Validate: "app/1.0/web/common/c.validate",
    cAjax: "app/1.0/web/common/c.ajax",
    cAbstractModel: "app/1.0/web/model/c.abstract.model",
    cModel: "app/1.0/web/model/c.model",
    cUserModel: "app/1.0/web/model/c.user.model",
    cMultipleDate: "app/1.0/web/model/c.multiple.data",
    memStore: "app/1.0/web/store/c.memorystore",
    cStore: "app/1.0/web/store/c.store",
    cStorage: "app/1.0/web/store/c.storage",
    CommonStore: "app/1.0/web/store/c.common.store",
    cUI: "app/1.0/web/ui/c.ui",
    cUICore: "app/1.0/web/ui/c.ui.core",
    cHistory: "app/1.0/web/ui/c.ui.history",
    cView: "app/1.0/web/ui/c.ui.view",
    cDataSource: "app/1.0/web/ui/c.ui.datasource",
    cUIAbstractView: "app/1.0/web/ui/c.ui.abstract.view",
    cAdView: "app/1.0/web/ui/c.ui.ad",
    cUIAlert: "app/1.0/web/ui/c.ui.alert",
    cUIAnimation: "app/1.0/web/ui/c.ui.animation",
    cUIBase: "app/1.0/web/ui/c.ui.base",
    cUIEventListener: "app/1.0/web/ui/c.ui.event.listener",
    cUIHashObserve: "app/1.0/web/ui/c.ui.hash.observe",
    cUIWarning: "app/1.0/web/ui/c.ui.warning",
    cUIHeadWarning: "app/1.0/web/ui/c.ui.head.warning",
    cUIInputClear: "app/1.0/web/ui/c.ui.input.clear",
    cUILayer: "app/1.0/web/ui/c.ui.layer",
    cUILoading: "app/1.0/web/ui/c.ui.loading",
    cUILoadingLayer: "app/1.0/web/ui/c.ui.loading.layer",
    cUIMask: "app/1.0/web/ui/c.ui.mask",
    cUIPageview: "app/1.0/web/ui/c.ui.page.view",
    cUIScrollRadio: "app/1.0/web/ui/c.ui.scroll.radio",
    cUIScrollRadioList: "app/1.0/web/ui/c.ui.scroll.radio.list",
    cUIScrollList: "app/1.0/web/ui/c.ui.scrolllist",
    cUIScrollLayer: "app/1.0/web/ui/c.ui.scrolllayer",
    cUIToast: "app/1.0/web/ui/c.ui.toast",
    cUIWarning404: "app/1.0/web/ui/c.ui.warning404",
    cUICitylist: "app/1.0/web/ui/c.ui.citylist",
    cWidgetFactory: "app/1.0/web/widget/c.widget.factory",
    cWidgetHeaderView: "app/1.0/web/widget/c.widget.headerview",
    cWidgetListView: "app/1.0/web/widget/c.widget.listview",
    cWidgetTipslayer: "app/1.0/web/widget/c.widget.tipslayer",
    cWidgetInputValidator: "app/1.0/web/widget/c.widget.inputValidator",
    cWidgetPublisher: "app/1.0/web/widget/c.widget.publisher",
    cWidgetGeolocation: "app/1.0/web/widget/c.widget.geolocation",
    cWidgetAbstractCalendar: "app/1.0/web/widget/c.widget.abstract.calendar",
    cWidgetCalendar: "app/1.0/web/widget/c.widget.calendar",
    cWidgetCalendarPrice: "app/1.0/web/widget/c.widget.calendar.price",
    cWidgetSlide: "app/1.0/web/widget/c.widget.slide",
    cWidgetMember: "app/1.0/web/widget/c.widget.member",
    cWidgetGuider: "app/1.0/web/widget/c.widget.guider",
    cWidgetCaptcha: "app/1.0/web/widget/c.widget.captcha",
    cBasePageView: "app/1.0/web/page/c.page.base",
    cCommonPageFactory: "app/1.0/web/page/c.page.factory",
    cCommonListPage: "app/1.0/web/page/c.page.common.list",
    cHybridFacade: "app/1.0/web/hybrid/c.hybrid.facade"
  }
});